import React from 'react';
import { makeStyles } from '@material-ui/core/styles';
import Table from '@material-ui/core/Table';
import TableBody from '@material-ui/core/TableBody';
import TableCell from '@material-ui/core/TableCell';
import TableContainer from '@material-ui/core/TableContainer';
import TableHead from '@material-ui/core/TableHead';
import TableRow from '@material-ui/core/TableRow';
import Paper from '@material-ui/core/Paper';

const useStyles = makeStyles({
  table: {
    maxWidth: 500,
    "& .MuiTableCell-root": {
      borderRight: "1px solid rgba(224, 224, 224, 1)" }
  },

  tableHead: {
    backgroundColor: '#ADD8E6'
  },

  tableRow: {
    padding: "1"
  },
});

function createCountry(abv, name) {
  return { abv, name };
}

const rows = [
    createCountry('AF', 'Afghanistan'),
    createCountry('AX', 'Åland Islands'),
    createCountry('AL', 'Albania'),
    createCountry('DZ', 'Algeria'),
    createCountry('AS', 'American Samoa'),
    createCountry('AD', 'Andorra'),
    createCountry('AO', 'Angola'),
    createCountry('AI', 'Anguilla'),
    createCountry('AQ', 'Antarctica'),
    createCountry('AG', 'Antigua and Barbuda'),
    createCountry('AR', 'Argentina'),
    createCountry('AM', 'Armenia'),
    createCountry('AW', 'Aruba'),
    createCountry('AU', 'Australia'),
    createCountry('AT', 'Austria'),
    createCountry('AZ', 'Azerbaijan'),
    createCountry('BS', 'Bahamas (the)'),
    createCountry('BH', 'Bahrain'),
    createCountry('BD', 'Bangladesh'),
    createCountry('BB', 'Barbados'),
    createCountry('BY', 'Belarus'),
    createCountry('BE', 'Belgium'),
    createCountry('BZ', 'Belize'),
    createCountry('BJ', 'Benin'),
    createCountry('BM', 'Bermuda'),
    createCountry('BT', 'Bhutan'),
    createCountry('BO', 'Bolivia (Plurinational State of)'),
    createCountry('BQ', 'Bonaire, Sint Eustatius and Saba'),
    createCountry('BA', 'Bosnia and Herzegovina'),
    createCountry('BW', 'Botswana'),
    createCountry('BV', 'Bouvet Island'),
    createCountry('BR', 'Brazil'),
    createCountry('IO', 'British Indian Ocean Territory(the)'),
    createCountry('BN', 'Brunei Darussalam'),
    createCountry('BG', 'Bulgaria'),
    createCountry('BF', 'Burkina Faso'),
    createCountry('BI', 'Burundi'),
    createCountry('CV', 'Cabo Verde'),
    createCountry('KH', 'Cambodia'),
    createCountry('CM', 'Cameroon'),
    createCountry('CA', 'Canada'),
    createCountry('KY', 'Cayman Islands (the)'),
    createCountry('CF', 'Central African Republic (the)'),
    createCountry('TD', 'Chad'),
    createCountry('CL', 'Chile'),
    createCountry('CN', 'China'),
    createCountry('CX', 'Christmas Island'),
    createCountry('CC', 'Cocos (Keeling) Islands (the)'),
    createCountry('CO', 'Colombia'),
    createCountry('KM', 'Comoros (the)'),
    createCountry('CD', 'Congo (the Democratic Republic of the)'),
    createCountry('CG', 'Congo (the)'),
    createCountry('CK', 'Cook Islands (the)'),
    createCountry('CR', 'Costa Rica'),
    createCountry('HR', 'Croatia'),
    createCountry('CU', 'Cuba'),
    createCountry('CW', 'Curaçao'),
    createCountry('CY', 'Cyprus'),
    createCountry('CZ', 'Czechia'),
    createCountry('CI', 'Côte d\'Ivoire'),
    createCountry('DK', 'Denmark'),
    createCountry('DJ', 'Djibouti'),
    createCountry('DM', 'Dominica'),
    createCountry('DO', 'Dominican Republic (the)'),
    createCountry('EC', 'Ecuador'),
    createCountry('EG', 'Egypt'),
    createCountry('SV', 'El Salvador'),
    createCountry('GQ', 'Equatorial Guinea'),
    createCountry('ER', 'Eritrea'),
    createCountry('EE', 'Estonia'),
    createCountry('SZ', 'Eswatini'),
    createCountry('ET', 'Ethiopia'),
    createCountry('FK', 'Falkland Islands (the) [Malvinas]'),
    createCountry('FO', 'Faroe Islands (the)'),
    createCountry('FJ', 'Fiji'),
    createCountry('FI', 'Finland'),
    createCountry('FR', 'France'),
    createCountry('GF', 'French Guiana'),
    createCountry('PF', 'French Polynesia'),
    createCountry('TF', 'French Southern Territories (the)'),
    createCountry('GA', 'Gabon'),
    createCountry('GM', 'Gambia (the)'),
    createCountry('GE', 'Georgia'),
    createCountry('DE', 'Germany'),
    createCountry('GH', 'Ghana'),
    createCountry('GI', 'Gibraltar'),
    createCountry('GR', 'Greece'),
    createCountry('GL', 'Greenland'),
    createCountry('GD', 'Grenada'),
    createCountry('GP', 'Guadeloupe'),
    createCountry('GU', 'Guam'),
    createCountry('GT', 'Guatemala'),
    createCountry('GG', 'Guernsey'),
    createCountry('GN', 'Guinea'),
    createCountry('GW', 'Guinea-Bissau'),
    createCountry('GY', 'Guyana'),
    createCountry('HT', 'Haiti'),
    createCountry('HM', 'Heard Island and McDonald Islands'),
    createCountry('VA', 'Holy See (the)'),
    createCountry('HN', 'Honduras'),
    createCountry('HK', 'Hong Kong'),
    createCountry('HU', 'Hungary'),
    createCountry('IS', 'Iceland'),
    createCountry('IN', 'India'),
    createCountry('ID', 'Indonesia'),
    createCountry('IR', 'Iran (Islamic Republic of)'),
    createCountry('IQ', 'Iraq'),
    createCountry('IE', 'Ireland'),
    createCountry('IM', 'Isle of Man'),
    createCountry('IL', 'Israel'),
    createCountry('IT', 'Italy'),
    createCountry('JM', 'Jamaica'),
    createCountry('JP', 'Japan'),
    createCountry('JE', 'Jersey'),
    createCountry('JO', 'Jordan'),
    createCountry('KZ', 'Kazakhstan'),
    createCountry('KE', 'Kenya'),
    createCountry('KI', 'Kiribati'),
    createCountry('KP', 'Korea (the Democratic People\'s Republic of)'),
    createCountry('KR', 'Korea (the Republic of)'),
    createCountry('KW', 'Kuwait'),
    createCountry('KG', 'Kyrgyzstan'),
    createCountry('LA', 'Lao People\'s Democratic Republic (the)'),
    createCountry('LV', 'Latvia'),
    createCountry('LB', 'Lebanon'),
    createCountry('LS', 'Lesotho'),
    createCountry('LR', 'Liberia'),
    createCountry('LY', 'Libya'),
    createCountry('LI', 'Liechtenstein'),
    createCountry('LT', 'Lithuania'),
    createCountry('LU', 'Luxembourg'),
    createCountry('MO', 'Macao'),
    createCountry('MG', 'Madagascar'),
    createCountry('MW', 'Malawi'),
    createCountry('MY', 'Malaysia'),
    createCountry('MV', 'Maldives'),
    createCountry('ML', 'Mali'),
    createCountry('MT', 'Malta'),
    createCountry('MH', 'Marshall Islands (the)'),
    createCountry('MQ', 'Martinique'),
    createCountry('MR', 'Mauritania'),
    createCountry('MU', 'Mauritius'),
    createCountry('YT', 'Mayotte'),
    createCountry('MX', 'Mexico'),
    createCountry('FM', 'Micronesia (Federated States of)'),
    createCountry('MD', 'Moldova (the Republic of)'),
    createCountry('MC', 'Monaco'),
    createCountry('MN', 'Mongolia'),
    createCountry('ME', 'Montenegro'),
    createCountry('MS', 'Montserrat'),
    createCountry('MA', 'Morocco'),
    createCountry('MZ', 'Mozambique'),
    createCountry('MM', 'Myanmar'),
    createCountry('NA', 'Namibia'),
    createCountry('NR', 'Nauru'),
    createCountry('NP', 'Nepal'),
    createCountry('NL', 'Netherlands (the)'),
    createCountry('NC', 'New Caledonia'),
    createCountry('NZ', 'New Zealand'),
    createCountry('NI', 'Nicaragua'),
    createCountry('NE', 'Niger (the)'),
    createCountry('NG', 'Nigeria'),
    createCountry('NU', 'Niue'),
    createCountry('NF', 'Norfolk Island'),
    createCountry('MP', 'Northern Mariana Islands (the)'),
    createCountry('NO', 'Norway'),
    createCountry('OM', 'Oman'),
    createCountry('PK', 'Pakistan'),
    createCountry('PW', 'Palau'),
    createCountry('PS', 'Palestine, State of'),
    createCountry('PA', 'Panama'),
    createCountry('PG', 'Papua New Guinea'),
    createCountry('PY', 'Paraguay'),
    createCountry('PE', 'Peru'),
    createCountry('PH', 'Philippines (the)'),
    createCountry('PN', 'Pitcairn'),
    createCountry('PL', 'Poland'),
    createCountry('PT', 'Portugal'),
    createCountry('PR', 'Puerto Rico'),
    createCountry('QA', 'Qatar'),
    createCountry('MK', 'Republic of North Macedonia'),
    createCountry('RO', 'Romania'),
    createCountry('RU', 'Russian Federation (the)'),
    createCountry('RW', 'Rwanda'),
    createCountry('RE', 'Réunion'),
    createCountry('BL', 'Saint Barthélemy'),
    createCountry('SH', 'Saint Helena, Ascension and Tristan da Cunha'),
    createCountry('KN', 'Saint Kitts and Nevis'),
    createCountry('LC', 'Saint Lucia'),
    createCountry('MF', 'Saint Martin (French part)'),
    createCountry('PM', 'Saint Pierre and Miquelon'),
    createCountry('VC', 'Saint Vincent and the Grenadines'),
    createCountry('WS', 'Samoa'),
    createCountry('SM', 'San Marino'),
    createCountry('ST', 'Sao Tome and Principe'),
    createCountry('SA', 'Saudi Arabia'),
    createCountry('SN', 'Senegal'),
    createCountry('RS', 'Serbia'),
    createCountry('SC', 'Seychelles'),
    createCountry('SL', 'Sierra Leone'),
    createCountry('SG', 'Singapore'),
    createCountry('SX', 'Sint Maarten (Dutch part)'),
    createCountry('SK', 'Slovakia'),
    createCountry('SI', 'Slovenia'),
    createCountry('SB', 'Solomon Islands'),
    createCountry('SO', 'Somalia'),
    createCountry('ZA', 'South Africa'),
    createCountry('GS', 'South Georgia and the South Sandwich Islands'),
    createCountry('SS', 'South Sudan'),
    createCountry('ES', 'Spain'),
    createCountry('LK', 'Sri Lanka'),
    createCountry('SD', 'Sudan (the)'),
    createCountry('SR', 'Suriname'),
    createCountry('SJ', 'Svalbard and Jan Mayen'),
    createCountry('SE', 'Sweden'),
    createCountry('CH', 'Switzerland'),
    createCountry('SY', 'Syrian Arab Republic'),
    createCountry('TW', 'Taiwan (Province of China)'),
    createCountry('TJ', 'Tajikistan'),
    createCountry('TZ', 'Tanzania, United Republic of'),
    createCountry('TH', 'Thailand'),
    createCountry('TL', 'Timor-Leste'),
    createCountry('TG', 'Togo'),
    createCountry('TK', 'Tokelau'),
    createCountry('TO', 'Tonga'),
    createCountry('TT', 'Trinidad and Tobago'),
    createCountry('TN', 'Tunisia'),
    createCountry('TR', 'Turkey'),
    createCountry('TM', 'Turkmenistan'),
    createCountry('TC', 'Turks and Caicos Islands (the)'),
    createCountry('TV', 'Tuvalu'),
    createCountry('UG', 'Uganda'),
    createCountry('UA', 'Ukraine'),
    createCountry('AE', 'United Arab Emirates (the)'),
    createCountry('GB', 'United Kingdom of Great Britain and Northern Ireland (the)'),
    createCountry('UM', 'United States Minor Outlying Islands (the)'),
    createCountry('US', 'United States of America (the)'),
    createCountry('UY', 'Uruguay'),
    createCountry('UZ', 'Uzbekistan'),
    createCountry('VU', 'Vanuatu'),
    createCountry('VE', 'Venezuela (Bolivarian Republic of)'),
    createCountry('VN', 'Viet Nam'),
    createCountry('VG', 'Virgin Islands (British)'),
    createCountry('VI', 'Virgin Islands (U.S.)'),
    createCountry('WF', 'Wallis and Futuna'),
    createCountry('EH', 'Western Sahara'),
    createCountry('YE', 'Yemen'),
    createCountry('ZM', 'Zambia'),
    createCountry('ZW', 'Zimbabwe'), 
];

export default function BasicTable() {
  const classes = useStyles();

  return (
    <TableContainer component={Paper}>
      <Table className={classes.table} aria-label="simple table">
        <TableHead className={classes.tableHead}>
          <TableRow>
            <TableCell>Country Name</TableCell>
            <TableCell align ="right">Abbreviation</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {rows.map((row) => (
            <TableRow key={row.name}>
              <TableCell component="th" scope="row">
                {row.name}
              </TableCell>
              <TableCell align="right">{row.abv}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  );
}
